USE [master]
GO

/****** Object:  Database [UsersDB]    Script Date: 29/07/2014 11:42:27 ******/
CREATE DATABASE [UsersDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UsersDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\UsersDB.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UsersDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\UsersDB_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [UsersDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UsersDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UsersDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UsersDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UsersDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UsersDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UsersDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [UsersDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UsersDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [UsersDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UsersDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UsersDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UsersDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UsersDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UsersDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UsersDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UsersDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UsersDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [UsersDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UsersDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UsersDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UsersDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UsersDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UsersDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UsersDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UsersDB] SET RECOVERY FULL 
GO

ALTER DATABASE [UsersDB] SET  MULTI_USER 
GO

ALTER DATABASE [UsersDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UsersDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UsersDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UsersDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UsersDB] SET  READ_WRITE 
GO


